.eslintrc.js
.gitignore
.prettierrc
nest-cli.json
package-lock.json
package.json
readme.md
src/app.controller.spec.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/main.ts
test/app.e2e-spec.ts
test/jest-e2e.json
tsconfig.build.json
tsconfig.json

initialized the repo and added all necessary settings and configurations for smooth progress.
closes #1

added all necessary settings and configs

---

package-lock.json
package.json
src/capsule/entities/capsule.entity.ts
src/guest/entities/guest.entity.ts
src/transaction/entities/transaction.entity.ts
src/user/entities/user.entity.ts

implemented entities for the resources

---

.env.development
config/database.config.ts
package-lock.json
package.json
src/app.module.ts

- **Implemented environment configuration:** Installed `@nestjs/config` and `dotenv`, created a `.env.development` file, and set up a `config/database.config.ts` file for structured environment settings.  
- **Updated `app.module.ts` for dynamic configuration:** Integrated `ConfigModule` and `TypeOrmModule` to load database settings dynamically based on the environment.  
- **Followed project structure and GitHub setup:** Ensured the configuration files were correctly placed, committed the changes, and pushed the code to GitHub.

Configure Application Environment and Production Settings #3

---

.env.development
package-lock.json
package.json
src/app.module.ts
src/auth/auth.module.ts
src/auth/config/jwt.config.ts
src/auth/provider/bcrpt.provider.ts
src/auth/provider/generate-token.provider.ts
src/auth/provider/hashing.provider.ts
src/user/entities/user.entity.ts

create the abstract hashing provider
implement the bcrypt provider

"feat: create the hashing provider and implemented it"

---

src/user/entities/user.entity.ts

Implement Relationships Between Entities

---

.env.development
config/database.config.ts
package-lock.json
package.json
src/auth/auth.module.ts
src/auth/auth.service.ts
src/auth/dto/refresh-token.dto.ts
src/auth/provider/refreshToken.provider.ts
src/capsule/entities/capsule.entity.ts
src/guest/entities/guest.entity.ts
src/guest/guest.module.ts
src/user/entities/user.entity.ts
src/user/user.service.ts

create refresh token provider
create the refresh token provider

"feat: refresh token"

---

src/capsule/dto/create-capsule.dto.ts
src/guest/dto/create-guest.dto.ts
src/main.ts
src/transaction/dto/create-transaction.dto.ts
src/user/dto/create-user.dto.ts

All DTOs are now implemented.
I have also incoporated:
✅ Ensures all incoming requests follow DTO rules
✅ Automatically removes unexpected fields (whitelist)
✅ Prevents users from sending extra data (forbidNonWhitelisted)
✅ Converts request body values to expected types (transform)

corrected: implemented DTOs for User, Capsule, Guest Capsule Access Log

---

src/admin/admin.controller.spec.ts
src/admin/admin.controller.ts
src/admin/admin.module.ts
src/admin/admin.service.spec.ts
src/admin/admin.service.ts
src/admin/dto/create-admin.dto.ts
src/admin/dto/update-admin.dto.ts
src/admin/entities/admin.entity.ts
src/app.module.ts

setup admin resources

---

.gitignore
src/user/dto/update-user.dto.ts
src/user/entities/user.entity.ts
src/user/http/update.http
src/user/user.controller.ts
src/user/user.service.ts

Implement User Update Endpoint with Validation

Implement User Update Endpoint with Validation

---

src/app.module.ts
src/common/data-response/data-response-interceptor.interceptor.ts
src/common/pagination/pagination.module.ts
src/common/pagination/pagination.service.ts
src/get.endpoints.http

feat: Add global interceptor

---

src/analytics/analytics.module.ts
src/analytics/constants/analytics.constants.ts
src/analytics/controllers/analytics.controller.ts
src/analytics/decorators/analytics-roles.decorator.ts
src/analytics/dto/aggregated-analytics.dto.ts
src/analytics/dto/analytics-response.dto.ts
src/analytics/dto/date-range.dto.ts
src/analytics/dto/player-engagement.dto.ts
src/analytics/entities/player-engagement.entity.ts
src/analytics/entities/song-category.entity.ts
src/analytics/entities/token.entity.ts
src/analytics/entities/user-progression.entity.ts
src/analytics/enums/analytics-role.enum.ts
src/analytics/guards/analytics-auth.guard.ts
src/analytics/guards/analytics-roles.guard.ts
src/analytics/interfaces/analytics.interface.ts
src/analytics/repositories/analytics.repository.ts
src/analytics/services/analytics-aggregator.service.ts
src/analytics/services/player-engagement.service.ts
src/analytics/services/song-analytics.service.ts
src/analytics/services/token-analytics.service.ts
src/analytics/services/user-progression.service.ts

added analytics and report system

---

src/language/controllers/admin-translation.controller.ts
src/language/controllers/language-detection.controller.ts
src/language/controllers/puzzle-translation.controller.ts
src/language/controllers/translation.controller.ts
src/language/controllers/user-language.controller.ts
src/language/dto/create-language.dto.ts
src/language/dto/create-user-language.dto.ts
src/language/dto/update-language.dto.ts
src/language/dto/update-user-language.dto.ts
src/language/entities/language.entity.ts
src/language/entities/puzzle-translation.entity.ts
src/language/entities/puzzle.entity.ts
src/language/entities/translation-key.entity.ts
src/language/entities/translation.entity.ts
src/language/entities/user-language-preference.entity.ts
src/language/language.module.ts
src/language/repositories/language.repository.ts
src/language/repositories/puzzle-translation.repository.ts
src/language/repositories/puzzle.repository.ts
src/language/repositories/translation-key.repository.ts
src/language/repositories/translation.repository.ts
src/language/repositories/user-language.repository.ts
src/language/services/admin-translation.service.ts
src/language/services/cache.service.ts
src/language/services/event-emitter.service.ts
src/language/services/language-detection.service.ts
src/language/services/puzzle-translation.service.ts
src/language/services/translation.service.ts
src/language/services/user-language.service.ts

added language support

---

package-lock.json
src/admin/admin.controller.ts
src/admin/admin.service.spec.ts
src/admin/admin.service.ts

Created an endpoint for admin to retrieve all capsules

Initial commit with respect to the endpoint on admins findingallcapsules

---

src/socials/dto/socials.dto.ts
src/socials/entities/activity.entity.ts
src/socials/entities/follow.entity.ts
src/socials/socials.controllers.ts
src/socials/socials.module..ts
src/socials/socials.service.ts

Add social module with follow and activity functionality

---

src/leaderboard/analytics.module.ts
src/leaderboard/controllers/leaderboard.controller.ts
src/leaderboard/dtos/leaderboard-filter.dto.ts
src/leaderboard/dtos/leaderboard-response.dto.ts
src/leaderboard/entities/contribution.entity.ts
src/leaderboard/entities/user.entity.ts
src/leaderboard/enums/contribution-type.enum.ts
src/leaderboard/services/contribution.service.ts
src/leaderboard/services/leaderboard.service.ts

feat: Add leader Leader board resources

---

src/chat/chat.module.ts
src/chat/controllers/chat.controller.ts
src/chat/controllers/group.controller.ts
src/chat/dto/add-member.dto.ts
src/chat/dto/create-group.dto.ts
src/chat/dto/send-message.dto.ts
src/chat/dto/update-group.dto.ts
src/chat/dto/update-member-role.dto.ts
src/chat/dto/update-message-status.dto.ts
src/chat/entities/attachment.entity.ts
src/chat/entities/chat-group.entity.ts
src/chat/entities/group-member.entity.ts
src/chat/entities/message.entity.ts
src/chat/gateways/chat.gateway.ts
src/chat/services/chat.service.ts
src/chat/services/group.service.ts

add chat resources

---

src/webhooks/dto/create-subscription.dto.ts
src/webhooks/dto/update-subscription.dto.ts
src/webhooks/entities/webhook-delivery.entity.ts
src/webhooks/entities/webhook-event.entity.ts
src/webhooks/entities/webhook-subscription.entity.ts
src/webhooks/interfaces/webhook-event-types.interface.ts
src/webhooks/webhooks-admin.controller.ts
src/webhooks/webhooks-event-emitter.service.ts
src/webhooks/webhooks.controller.ts
src/webhooks/webhooks.module.ts
src/webhooks/webhooks.service.ts

feat(webhooks): add endpoints for managing webhook subscriptions and deliveries
- Implemented endpoints to create, update, delete, and retrieve webhook subscriptions.
- Added endpoint to retrieve deliveries for a specific subscription.
- Added endpoint to retry a specific delivery.
- Secured endpoints with JWT authentication.
closes #73

feat(webhooks): add endpoints for managing webhook subscriptions

---

src/app.module.ts
src/public-capsule/dto/create-public-capsule.dto.ts
src/public-capsule/dto/public-capsule-response.dto.ts
src/public-capsule/dto/update-public-capsule.dto.ts
src/public-capsule/public-capsule.module.ts
src/public-capsule/publicCapsule.entity.ts

Description:
This PR introduces a PublicCapsule entity, a publicly accessible repository for capsule-related data, distinct from regular capsules. It includes entity definition, schema updates, and migration implementation in NestJS with TypeORM & PostgreSQL.
Key Features & Enhancements:
PublicCapsule Entity with the specified following fields
✅ Database Schema & Migration:
Created a new public_capsules table.
Established a foreign key relationship between creatorId and users.id.
Added migration scripts to ensure smooth schema updates.
✅ Technical Considerations:
Ensured PublicCapsule logic is separate from regular capsules.
Implemented data validation to prevent inconsistencies.
Followed NestJS project structure for maintainability.
🛠️ Implementation Details:
PublicCapsule Entity: …

Implemented Public Capsule Entity & Database Schema

---

src/app.module.ts
src/capsule/capsule.service.ts
src/capsule/entities/capsule.entity.ts
src/user-interaction/dto/create-user-interaction.dto.ts
src/user-interaction/dto/update-user-interaction.dto.ts
src/user-interaction/entities/user-interaction.entity.ts
src/user-interaction/user-interaction.controller.spec.ts
src/user-interaction/user-interaction.controller.ts
src/user-interaction/user-interaction.module.ts
src/user-interaction/user-interaction.service.spec.ts
src/user-interaction/user-interaction.service.ts
src/user/entities/user.entity.ts

This PR adds user interactions for capsule recommendations extending the `user` and `capsule` entity
Closes #100 
N/A
N/A
N/A

feat: add user interactinos for capsule recommendations

---

src/capsule/entities/capsule.entity.ts
src/recommendation/recommendation.controller.spec.ts
src/recommendation/recommendation.controller.ts
src/recommendation/recommendation.module.ts
src/recommendation/recommendation.service.spec.ts
src/recommendation/recommendation.service.ts
src/user/entities/user.entity.ts

This PR Implement a recommendation engine and corresponding API to provide personalized capsule suggestions.
Closes #101
N/A
N/A
N/A

feat: add new recommendation engine api suggestion

---

src/locked-funds/dto/cancel-lock.dto.ts
src/locked-funds/dto/lock-funds.dto.ts
src/locked-funds/entities/locked-funds.entity.ts
src/locked-funds/locked-funds.controller.ts
src/locked-funds/locked-funds.module.ts
src/locked-funds/locked-funds.scheduler.ts
src/locked-funds/locked-funds.service.ts

This PR implements a secure fund locking system that enables temporary balance holds with scheduled releases, supporting time-locked savings and escrow-like services.
- POST /funds/lock: Creates new locked fund record
- POST/funds/release-expired: Admin endpoint for manual trigger
- POST/funds/cancel/:id: Cancels locked funds (with validation)

Implement Time-Locked Funds Mechanism for Scheduled Financial Transactions

---

src/reports/dto/create-report.dto.ts
src/reports/dto/report-query.dto.ts
src/reports/dto/update-report.dto.ts
src/reports/entities/report.entity.ts
src/reports/reports.controller.ts
src/reports/reports.module.ts
src/reports/reports.service.ts

Task Overview: User-Reported Content System
Implement a feature allowing users to report inappropriate content in time capsules.
Create a Report entity to store details like capsule ID, reason for reporting, user ID, and report status.
Develop two API endpoints: one for users to submit reports and another for admins to view pending reports.
Ensure proper validation, error handling, and role-based access control.
Include unit and integration tests to verify functionality.

 Implement User Content Reporting for Time Capsules

---

src/src/users/dto/create-user.dto.ts
src/src/users/dto/update-user.dto.ts
src/src/users/schemas/user.schema.ts
src/src/users/users.controller.ts
src/src/users/users.module.ts
src/src/users/users.service.ts

- Created the `UsersController` to handle both user and admin endpoints
- Implemented profile endpoints:
- `GET /users/me` to retrieve the current user's profile
- `PATCH /users/me` to update the current user's profile
- Added admin endpoints for user management:
- `GET /admin/users` with pagination
- `POST /admin/users` to create a new user
- `PATCH /admin/users/:id` to update an existing user
- `DELETE /admin/users/:id` to remove a user
- Created DTOs for user creation and update operations
- Added role-based access control using guards
- Built custom decorators:
- `@CurrentUser()` to inject the authenticated user
- `@Roles('admin')` to restrict access to admin-only routes
- Implemented pagination support for listing users
- Added basic validation and error handling
---
- Verified all …

added the user resource

---

src/src/auth/auth.controller.ts
src/src/auth/auth.module.ts
src/src/auth/auth.service.ts
src/src/auth/decorators/current-user.decorator.ts
src/src/auth/decorators/public.decorator.ts
src/src/auth/dto/forgot-password.dto.ts
src/src/auth/dto/login.dto.ts
src/src/auth/dto/register.dto.ts
src/src/auth/dto/reset-password.dto.ts
src/src/auth/guards/jwt-auth.guard.ts
src/src/auth/password-recovery.controller.ts
src/src/auth/password-recovery.service.ts
src/src/auth/schemas/password-reset.schema.ts
src/src/auth/strategies/jwt.strategy.ts

<p>This PR introduces the <strong>complete authentication system</strong> for the backend of the ManageHub platform. It follows <strong>NestJS best practices</strong>, ensuring security, scalability, and clarity in the authentication workflow. The system supports both <strong>guest sessions</strong> and full <strong>user account management</strong>, with support for <strong>JWT-based access and refresh tokens</strong>, session invalidation, and secure password handling.</p>
<hr>
<h2>🎯 Key Features Implemented:</h2>
<h3>🔑 1. <strong>Authentication Module</strong></h3>
<ul>
<li>
<p>Created <code inline="">AuthModule</code>, <code inline="">AuthService</code>, and <code inline="">AuthController</code> to handle all auth-related logic</p>
</li>
<li>
<p>Modular structure allows for scalability …

Implement Core Authentication and Session Management (Login, Register, Logout, Token Refresh)

---

src/app.module.ts
src/main.ts
src/src/common/filters/http-exception.filter.ts
src/src/common/interceptors/transform.interceptor.ts
src/src/common/middleware/security.middleware.ts
src/src/common/pipes/validation.pipe.ts

I implemented a global middleware layer to enhance security and validation across the entire application.
- **Input Validation**:  
Set up global validation pipes using NestJS’s built-in features to ensure consistent and centralized input validation.
- **CORS Configuration**:  
Configured CORS settings globally to control cross-origin access to our APIs.
- **Security Headers with Helmet**:  
Integrated `helmet` middleware to set secure HTTP headers and improve protection against common web vulnerabilities.
- **Rate Limiting**:  
Introduced a custom `RateLimiterMiddleware`, currently applied to sensitive endpoints like login, to prevent brute-force attacks and abuse.
- **Exception Filters**:  
Added a centralized exception filter to uniformly handle and format errors across the …

Added global security middleware

---

src/app.module.ts
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/auth.service.ts
src/auth/decorators/current-user.decorator.ts
src/auth/decorators/guest-allowed.decorator.ts
src/auth/decorators/public.decorator.ts
src/auth/decorators/roles.decorator.ts
src/auth/dto/forgot-password.dto.ts
src/auth/dto/login.dto.ts
src/auth/dto/reset-password.dto.ts
src/auth/dto/upgrade-guest.dto.ts
src/auth/guards/guest-or-auth.guard.ts
src/auth/guards/no-guests.guard.ts
src/auth/guards/verified.guard.ts
src/auth/middleware/guest-user.middleware.ts
src/auth/password-recovery.controller.ts
src/auth/password-recovery.service.ts
src/auth/schemas/password-reset.schema.ts
src/auth/strategies/jwt.strategy.ts
src/users/admin-users.controller.ts
src/users/dto/create-user.dto.ts
src/users/dto/update-user.dto.ts
src/users/schemas/user.schema.ts
src/users/users.controller.ts
src/users/users.module.ts
src/users/users.service.ts

This PR implements support for guest users across all authentication-related flows, ensuring a smooth transition from guest to registered user and proper access control based on user type.
---
- 👥 **Guest User Handling**
- Automatically creates guest users on first access.
- Upgrades guest users during registration via `upgradeGuestToUser()` service method.
- 🧠 **User Type Detection**
- Middleware/service helper added to identify and handle guest users.
- Controllers now differentiate between:
- Guests
- Registered Users
- Admins
- 🔐 **Session/JWT Payload**
- Extended with `guest: true` flag for easy identification.
---
Closes #122

feat: add guest user flow handling

---

package-lock.json
package.json
src/app.module.ts
src/capsules/capsules.service.ts
src/capsules/dto/create-capsule.dto.ts
src/capsules/dto/update-capsule.dto.ts
src/funds/dto/create-fund.dto.ts
src/funds/dto/update-fund.dto.ts
src/funds/funds.service.ts
src/geolocks/dto/create-geolock.dto.ts
src/geolocks/dto/update-geolock.dto.ts
src/geolocks/geolocks.service.ts
src/media/dto/create-media.dto.ts
src/media/dto/update-media.dto.ts
src/media/media.service.ts
src/models/capsule.schema.ts
src/models/fund.schema.ts
src/models/geolock.schema.ts
src/models/media.schema.ts
src/models/user.schema.ts
src/users/dto/create-user.dto.ts
src/users/dto/update-user.dto.ts
src/users/users.module.ts
src/users/users.service.ts

This PR sets up the core data models and infrastructure for the application. It introduces Mongoose schemas and implements basic CRUD operations for the following entities:
- **Capsule**
- **Media**
- **Fund**
- **Geolock**
- **User** (with support for collaborator roles)
- Defined Mongoose schemas with appropriate fields and relationships
- Implemented create, read, update, and delete operations for each model
- Added schema-level validation and indexes where applicable
- Included helper utilities and sample seed data for testing and local development
Closes #131

feat: add DTOs for creating funds, media, capsules, geolocks, and users

---

src/media/dto/media-query.dto.ts
src/media/dto/presigned-url-response.dto.ts
src/media/dto/presigned-url.dto.ts
src/media/dto/update-media.dto.ts
src/media/media.controller.ts
src/media/media.module.ts
src/media/media.service.ts
src/storage/storage.service.ts

This pull request introduces the core functionality for handling media uploads, specifically:
- Presigned upload URLs
- Final `storageUrl` return
- Support for encrypted (password-protected) uploads
---
- **Endpoint:** `GET /media/presign?fileName=&fileType=`
- **Returns:**
- `uploadUrl`: A presigned URL from the storage provider (e.g., S3).
- `storageUrl`: The final accessible URL after successful upload.
- For password-protected uploads, the file path will be prefixed with `encrypted/`.
- Example:
- Input: `fileName=report.pdf`
- If protected → Path: `encrypted/report.pdf`
- Ensures `fileName` and `fileType` are required query parameters.
- Validates acceptable MIME types (optional enhancement, can be added later).
---
- Enforces path prefixing for sensitive uploads (`encrypted/`).
- …

Implement Media and Storage
